# Generated by Django 2.1.3 on 2018-12-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_remove_merchant_admin'),
        ('product', '0079_product_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='merchant.Merchant'),
        ),
    ]
