# Generated by Django 2.1.3 on 2018-12-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_merchant_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='admin',
        ),
    ]
