# Generated by Django 2.1.3 on 2018-11-28 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
        ('order', '0067_auto_20181102_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='merchant.Merchant'),
        ),
    ]
