# Generated by Django 2.1.3 on 2018-11-28 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
        ('account', '0023_auto_20180719_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='merchant.Merchant'),
        ),
    ]
