# Generated by Django 2.1.3 on 2018-11-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_user_merchant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('manage_users', 'Manage customers.'), ('manage_staff', 'Manage staff.'), ('impersonate_users', 'Impersonate customers.'), ('manage_merchants', 'Manage merchants.'))},
        ),
    ]
