# Generated by Django 2.1.3 on 2018-12-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20181128_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
    ]
